# Generated by Django 6.0.3 on 2026-05-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload a short video', null=True, upload_to='media/posts/videos/'),
        ),
    ]
