# Generated by Django 6.0.3 on 2026-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_remove_post_image_url_post_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL', null=True),
        ),
    ]
